#!/bin/bash
#   Copyright 2012 Otavio Rodolfo Piske
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


# TODO: this is very simple stop script that I wrote in 5 minutes. I need
# to write a more robust version of this one.
# 

localdir=`dirname $0`
installdir=`dirname $localdir`

if [ "$installdir" = "." ] ; then
	installdir=".."
fi

if [ ! -f "$installdir"/bin/mdm.pid ] ; then
	echo "MDM broker is not running"
	exit 1
fi

pid=`cat "$installdir"/bin/mdm.pid`
echo "Checking if $pid is running"
is_running=`ps -ef | grep -i $pid | grep -v grep`

if [ x"$is_running" = "x" ] ; then
	echo "There's no MDM broker running with PID $pid"
	exit
fi


kill -TERM $pid

if [ $? -ne 0 ] ; then
	echo "Kill failed"
fi

sleep 1
is_running=`ps -ef | grep -i $pid | grep -v grep`
if [ x"$is_running" = "x" ] ; then
	rm "$installdir"/bin/mdm.pid
	echo "MDM broker stopped successfully"
	exit 0
else
	echo "MDM broker is still running ... forcing stop"
	sleep 1
	kill -9 $pid
	sleep 3

	is_running=`ps -ef | grep -i $pid | grep -v grep`
	if [ x"$is_running" = "x" ] ; then
		rm "$installdir"/bin/mdm.pid
		echo "MDM broker stopped successfully after SIGKILL"
		exit 0
	else
		echo "MDM broker failed to stop after SIGKILL"
		exit 1
	fi
fi
